#!/bin/env python3

import builtins
import argparse
import os, sys, subprocess
import re, rpm
import tempfile

def print(*args, **kwargs): # Auto-flush output
  try:
    builtins.print(*args, **kwargs, flush=True)
  except (BrokenPipeError, ConnectionResetError):
    sys.stdout = None
    sys.exit(0)

parser = argparse.ArgumentParser ( description = 'DNF Rollback' )

group1 = parser.add_mutually_exclusive_group(required=True)
group1.add_argument('--tid', type=str,
                    help='Use package list at transaction_id')
group1.add_argument('--pkgs', type=str, metavar='FILE',
                    help='Load package list from file')

group2 = parser.add_mutually_exclusive_group()
group2.add_argument('--dump', action='store_true',
                    help='Dump package list [default]')
group2.add_argument('--comm', action='store_true',
                    help='List dnf commands to rollback')
group2.add_argument('--exec', action='store_true',
                    help='Run dnf commands to rollback')

parser.add_argument('args', nargs='*', metavar='-- options',
                    help='Additional options to dnf shell')

opt = parser.parse_args()
if not ( opt.comm or opt.exec ): opt.dump = True

if opt.tid and not re.match(r'^last|(last-)?\d+$', opt.tid):
  parser.error(f"argument --tid: invalid transaction_id: '{opt.tid}'")
if opt.args and not opt.exec:
  parser.error(f"unrecognized arguments: {' '.join(opt.args)}")
for arg in opt.args:
  if arg[0] != '-': parser.error(f"unrecognized argument: {arg}")

def capture(command): # Capture command output
  if isinstance(command, str): command = command.split()
  return subprocess.run(command,
           capture_output=True, text=True, check=True
         ).stdout

pkg = { ls: {} for ls in ['old', 'new', 'pkg'] }

# Currently installed packages:
for package in capture('rpm -qa').splitlines():
  package = package.strip()
  pkg['new'][package] = None

# Use package list at transaction_id:

if opt.tid:
  pkg['old'] = pkg['new'].copy()

  tid2 = int(capture('dnf history last').splitlines()[2].split('|')[0].strip())
  if opt.tid == 'last':
    tid1 = tid2
  elif match := re.match(r'^last-(\d+)$', opt.tid):
    tid1 = tid2 - int(match.group(1))
  else:
    tid1 = int(opt.tid)

  # Process dnf transaction history:
  print('Processing', file=sys.stderr, end='')
  for tid in range(tid2, tid1, -1):
    for line in capture(f"dnf history info {str(tid)}").splitlines():
      if ( match := re.match(r'^\s+(?:\*+\s+)?(\w+(?:\s\w+)?)\s+(\S+)\s+\@\S+', line) ):
        action, package = match.groups()
        package = re.sub(r'-\d+:', '-', package)
        if   re.match(r'^(Reinstall(ed)?|Reason Change)$', action):
          if package not in pkg['old']:
            print(f"ERROR: {action} - {package} not installed.", file=sys.stderr)
            sys.exit(1)
        elif re.match(r'^(Install|Upgrade|Downgrade)$', action):
          if package not in pkg['old']:
            print(f"ERROR: {action} - {package} not installed.", file=sys.stderr)
            sys.exit(1)
          pkg['old'].pop(package, None)
        elif re.match(r'(Removed|Upgraded|Downgraded|Obsoleted)$', action):
          if package in pkg['old']:
            print(f"ERROR: {action} - {package} already exists.", file=sys.stderr)
            sys.exit(1)
          pkg['old'][package] = None
        else:
          print(f"ERROR: {action} - action unsupported.", file=sys.stderr)
          sys.exit(1)
    print('.', file=sys.stderr, end='')
  print('', file=sys.stderr)

# Load package list from file:

elif opt.pkgs:
  with ( sys.stdin if opt.pkgs == '-' else open(opt.pkgs, 'r') ) as f:
    for package in f:
      package = package.strip()
      pkg['old'][package] = None

# Dump package list:

if opt.dump:
  for package in sorted(pkg['old'].keys()):
    print(package)

else:
  kernel_version = capture('uname -r').strip() # Current running kernel
  pkg['pkg'] = { '_kernel': {}, '_kernel-*': {} } # kernels and sub-packages
  # Skip unchanged packages:
  for package in list(pkg['old'].keys()):
    if package in pkg['new']:
      pkg['old'].pop(package)
      pkg['new'].pop(package)
    elif match := re.match(r'^(.+)-([^-]+-[^-]+)\.[^.-]+$', package):
      if re.match(r'kernel-(.*-)?'+re.escape(kernel_version.split('-')[0])+r'-', package):
        pkg['pkg']['_kernel-*'][package] = None
        if match.group(1) == 'kernel':
          pkg['pkg']['_kernel'][match.group(2)] = None
      else:
        pkg['pkg'][match.group(1)] = None
  # Skip upgraded/downgraded packages:
  kernels = 0 # kernels removed
  for package in list(pkg['new'].keys()):
    p = re.match(r'^(.+)-[^-]+-[^-]+\.[^.-]+$', package)
    p = p.group(1) if p else ''
    if p in pkg['pkg'] or \
       re.match(r'kernel-(.*-)?'+re.escape(kernel_version)+r'$', package):
      if p == 'kernel': print(f"WARN: Cannot remove running kernel - {package}.", file=sys.stderr)
      pkg['new'].pop(package)
    elif p == 'kernel':
      kernels += 1
  # Careful not to install too many kernels:
  while len(pkg['pkg']['_kernel'].keys()) > kernels:
    pkg['pkg']['_kernel'].popitem()
  for package in pkg['pkg']['_kernel-*'].keys():
    v = re.match(r'^.+-([^-]+-[^-]+)\.[^.-]+$', package)
    if v and v.group(1) not in pkg['pkg']['_kernel'].keys():
      print(f"WARN: Insufficient kernel slots to install - {package}.", file=sys.stderr)
      pkg['old'].pop(package)

  # Generate dnf shell commands:
  commands = ''
  if pkg['old'].keys():
    commands += f"install {' '.join(pkg['old'].keys())}\n"
  if pkg['new'].keys():
    commands += f"remove {' '.join(pkg['new'].keys())}\n"
  if commands: commands += 'run\n'

  # List dnf commands to rollback:

  if not opt.exec:
    print(commands, end='')

  # Run dnf commands to rollback:

  else:
    with tempfile.NamedTemporaryFile() as tempfile:
      tempfile.write(commands.encode())
      tempfile.flush()
      subprocess.run(['sudo', 'dnf', 'shell', tempfile.name] + opt.args)
